//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WanderlustResource.Backend {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WanderlustResource.Backend.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired page number must be greater than zero!.
        /// </summary>
        public static string WLE001 {
            get {
                return ResourceManager.GetString("WLE001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must be greater than zero!.
        /// </summary>
        public static string WLE002 {
            get {
                return ResourceManager.GetString("WLE002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A predicate must be defined..
        /// </summary>
        public static string WLE003 {
            get {
                return ResourceManager.GetString("WLE003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one simple predicate must be given..
        /// </summary>
        public static string WLE004 {
            get {
                return ResourceManager.GetString("WLE004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected simple predicate!.
        /// </summary>
        public static string WLE005 {
            get {
                return ResourceManager.GetString("WLE005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} cannot be null!.
        /// </summary>
        public static string WLE006 {
            get {
                return ResourceManager.GetString("WLE006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformation of value comparing operator: {0} to expression is not supported!.
        /// </summary>
        public static string WLE007 {
            get {
                return ResourceManager.GetString("WLE007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password is not correct!.
        /// </summary>
        public static string WLE008 {
            get {
                return ResourceManager.GetString("WLE008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application failed to start correctly..
        /// </summary>
        public static string WLE009 {
            get {
                return ResourceManager.GetString("WLE009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Unit of Work is currently created!.
        /// </summary>
        public static string WLE010 {
            get {
                return ResourceManager.GetString("WLE010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with name {0} already exists!.
        /// </summary>
        public static string WLE011 {
            get {
                return ResourceManager.GetString("WLE011", resourceCulture);
            }
        }
    }
}
